INSERT INTO TB_ESTUDANTE (name) VALUES ('ESTUDANTE 1');
INSERT INTO TB_ESTUDANTE (name) VALUES ('ESTUDANTE 2');
INSERT INTO TB_ESTUDANTE (name) VALUES ('ESTUDANTE 3');
INSERT INTO TB_ESTUDANTE (name) VALUES ('ESTUDANTE 4');
INSERT INTO TB_ESTUDANTE (name) VALUES ('ESTUDANTE 5');